version: 0.4.{build}
skip_tags: true
configuration: Release
platform: AnyCPU
clone_depth: 2
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
  - choco install gitlink -y
before_build:
  - nuget restore
before_package:
  - del /S /Q packages\OpenCover.4.6.519\SampleSln packages\OpenCover.4.6.519\Samples
  - GitLink .\
  - nuget pack -Verbosity detailed "%APPVEYOR_PROJECT_NAME%.nuspec" -MSBuildVersion 14.0 -Properties id=%APPVEYOR_PROJECT_NAME%;version=%APPVEYOR_BUILD_VERSION%;author=Dapplo
after_test: 
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[%APPVEYOR_PROJECT_NAME%]* -[*]%APPVEYOR_PROJECT_NAME%.SimpleJson" -target:"packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"%APPVEYOR_PROJECT_NAME%.Tests\bin\release\%APPVEYOR_PROJECT_NAME%.Tests.dll -noshadow" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
environment:
  github_username:
    secure: dGUm8ikFV7zt04Snv/YfNA==
  github_token:
    secure: eBQPtXg53XgcvdcVY3wQAw6kkwNh+QhcsTDwzyQLLh6IOPyiePEaEhJR0D2YBjAj
  COVERALLS_REPO_TOKEN:
    secure: sVulFO20DgFcIIQPU926SJqzLWqv4EozRmXYa3MuSDz3fyFXie9wkptVMM5oz3nC
build:
  project: Dapplo.HttpExtensions.sln
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
artifacts:
- path: '*.nupkg'
  name: NuGet package
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: GitHub
  release: Dapplo.HttpExtensions-v$(appveyor_build_version)
  auth_token:
    secure: eBQPtXg53XgcvdcVY3wQAw6kkwNh+QhcsTDwzyQLLh6IOPyiePEaEhJR0D2YBjAj
  artifact: /.*\.nupkg/
  draft: false
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: xkDQ385+smLqdzhESsXBJvnUjK4FZ4Djjrqi9tFR29dwESIvPYOrQAqgri5Nf/fA