version: 0.6.{build}
skip_tags: true
configuration: Release
platform: AnyCPU
clone_depth: 2
branches:
  only:
  - master
install:
- choco install gitlink -y
before_build:
- ps: .\SetVersion.ps1
- appveyor-retry dotnet restore -v Minimal
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
before_package:
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { GitLink .\ }
after_test: 
- ps: .\CreateCoverage.ps1
environment:
  github_username:
    secure: dGUm8ikFV7zt04Snv/YfNA==
  github_token:
    secure: eBQPtXg53XgcvdcVY3wQAw6kkwNh+QhcsTDwzyQLLh6IOPyiePEaEhJR0D2YBjAj
  COVERALLS_REPO_TOKEN:
    secure: sVulFO20DgFcIIQPU926SJqzLWqv4EozRmXYa3MuSDz3fyFXie9wkptVMM5oz3nC
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
#cache:
#- '%USERPROFILE%\.nuget\packages'
artifacts:
- path: artifacts\**\*.*
  name: NuGet package
build_script:
- dotnet build Dapplo.HttpExtensions -c %CONFIGURATION% --no-dependencies
- dotnet build Dapplo.HttpExtensions.Tests -c %CONFIGURATION% --no-dependencies
after_build:
- dotnet pack Dapplo.HttpExtensions -c %CONFIGURATION% --no-build -o artifacts
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: xkDQ385+smLqdzhESsXBJvnUjK4FZ4Djjrqi9tFR29dwESIvPYOrQAqgri5Nf/fA
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/