version: 0.9.{build}
os: Visual Studio 2019
skip_tags: true
configuration: Release
platform: Any CPU
test: off
branches:
  only:
  - master
environment:
  github_username:
    secure: dGUm8ikFV7zt04Snv/YfNA==
  github_token:
    secure: eBQPtXg53XgcvdcVY3wQAw6kkwNh+QhcsTDwzyQLLh6IOPyiePEaEhJR0D2YBjAj
  CoverallsRepoToken:
    secure: sVulFO20DgFcIIQPU926SJqzLWqv4EozRmXYa3MuSDz3fyFXie9wkptVMM5oz3nC
  NuGetApiKey:
    secure: Fu7vXeOuWmvDK7WGNsEbTIV2vhDV4P6PiK5k1+UZOmwldhCfvUvkA4HOkml+ZE/n
# Install dotnet core 3.0 latest (alpha!!), as this is not provided on AppVeyor yet
install:
- ps: Invoke-WebRequest https://download.microsoft.com/download/9/0/1/901B684B-659E-4CBD-BEC8-B3F06967C2E7/NDP471-DevPack-ENU.exe -OutFile NDP471-DevPack-ENU.exe
- ps: Start-Process -FilePath "NDP471-DevPack-ENU.exe" -ArgumentList "/q","/norestart" -Wait
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/3.0.1xx/dotnet-sdk-latest-win-x64.exe'
- ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
build:
  verbosity: minimal
build_script:
- ps: .\build.ps1 --settings_skipverification=true --settings_skippackageversioncheck=true
cache:
  - tools -> tools/packages.config
artifacts:
- path: src\**\*.nupkg
- path: artifacts\**\site.zip
- path: artifacts\*.xml
- path: artifacts\*.html
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false